name: reconfirm-labels

on:
  issues:
  push:
    branches:
      - master
    paths:
      - '.github/labels.json'

jobs:
  labels:
    name: recreate-labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: lannonbr/issue-label-manager-action@2.0.0
        env:
          # Relies on .github/labels.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}